/* ✳ SIGNATURE — JAH-N Wiki Leaks Data Base generator. Property of Justin Addam Higgins (JAH).
   Boundless generator: produces NEW synthetic dossiers in the exact archive
   schema (id, kind, category, cat_code, subject, classification, overview,
   assessment, officer_conclusion, date_filed, sources). Deterministic: same
   seed + version => same record. Subjects are INVENTED — no real-world claims,
   no fabricated citations, no real names. Every dossier is labeled GENERATED
   and re-verified by an INDEPENDENT checker before acceptance. */
(function () {
  'use strict';
  var VERSION = 'jahdb-leaks-1.0';
  var ID_PREFIX = 'JAH-LEAK-';
  var STAMP = 'JAH-N Wiki Leaks Data Base — synthetic dossier. Generated; not a real file, not a real event.';

  /* the archive's real 10 categories, with their real cat codes */
  var CATS = [
    ['Mythology', 'MYTH'], ['UFOs & Extraterrestrial', 'UFO'], ['Cryptids', 'CRYPTID'],
    ['Pop-Fiction Tech', 'POPTECH'], ['Paranormal', 'PARA'], ['Dream Entities', 'DREAM'],
    ['Cosmic Anomalies', 'COSMIC'], ['Secret Programs', 'SECPROG'],
    ['Lost Technology', 'LOSTTECH'], ['Bio-Oddities', 'BIO']
  ];

  /* invented subject parts — synthetic compounds, no real-world referents */
  var ADJ = ['Glasswing', 'Hollowtone', 'Copperspine', 'Mistral', 'Ironveil',
    'Amberdrift', 'Stormhollow', 'Palefire', 'Thornwick', 'Silvermere'];
  var NOUN = ['Relay', 'Choir', 'Lattice', 'Harbor', 'Circuit',
    'Meadow', 'Vigil', 'Engine', 'Archive', 'Garden'];
  var PHEN = ['Hums', 'Flickers', 'Drifts', 'Signals', 'Echoes',
    'Blooms', 'Tides', 'Sparks', 'Whispers', 'Pulses'];
  var PLACES = ['Graywater Flats', 'Miller’s Crossing', 'the Alder Reach',
    'Beacon Hollow', 'Saltmarsh Point', 'the Copper Basin', 'Larkspur Vale'];
  var EXPERTS = ['Dr. I. Marsh', 'Dr. O. Bellwether', 'Dr. C. Fenn',
    'Dr. R. Ashdown', 'Dr. T. Quill', 'Dr. S. Harrow'];

  function ri(rnd, a, b) { return a + Math.floor(rnd() * (b - a + 1)); }
  function pick(rnd, arr) { return arr[Math.floor(rnd() * arr.length)]; }
  function iso(y, m, d) {
    return y + '-' + String(m).padStart(2, '0') + '-' + String(d).padStart(2, '0');
  }

  function buildSubject(adj, noun, phen) {
    return adj + ' ' + noun + ' ' + phen + ' — Simulated Field File';
  }
  function buildClassification(code) {
    return 'TOP SECRET // JAH-N // ' + code + ' // NOFORN';
  }
  function buildOverview(subj, nrep, place, year) {
    return 'Simulated field file on the ' + subj + ': ' + nrep + ' invented reports ' +
      'logged near ' + place + ' around ' + year + '. This dossier is synthetic — ' +
      'the subject, the reports, and the witnesses were generated for the boundless ' +
      'archive and describe no real event. The JAH-N assessment below treats the ' +
      'material as a simulation exercise only.';
  }
  function buildAssessment(subj, nrep) {
    return 'JAH-N simulation assessment of the ' + subj + '. Cross-check against the ' +
      'Signature Spec Catalog returned no corroborating drafts — expected, because this ' +
      'subject was generated, not observed. The ' + nrep + ' reports are internally ' +
      'consistent by construction and contradict no archived record. Conclusion of the ' +
      'simulation: coherent fiction, zero real-world weight.';
  }
  function buildConclusion(subj) {
    return 'Officer conclusion (simulation): the ' + subj + ' file is a generated ' +
      'exercise. No action, no real subject, no real witnesses. Filed as synthetic.';
  }

  function genDossier(rnd, opts) {
    opts = opts || {};
    var c = pick(rnd, CATS);
    if (opts.category) {
      var want = null;
      CATS.forEach(function (cc) { if (cc[0] === opts.category) want = cc; });
      if (want) c = want;
    }
    var adj = pick(rnd, ADJ), noun = pick(rnd, NOUN), phen = pick(rnd, PHEN);
    var subj = buildSubject(adj, noun, phen);
    var nrep = ri(rnd, 2, 9), place = pick(rnd, PLACES), year = ri(rnd, 1988, 2026);
    var y = ri(rnd, 2020, 2026), m = ri(rnd, 1, 12), d = ri(rnd, 1, 28);
    var panel = [pick(rnd, EXPERTS), pick(rnd, EXPERTS)];
    return {
      kind: 'bizarre',
      category: c[0], cat_code: c[1],
      subject: subj,
      classification: buildClassification(c[1]),
      overview: buildOverview(subj, nrep, place, year),
      assessment: buildAssessment(subj, nrep),
      science_proof: 'Simulation only — no physical evidence claimed or implied.',
      math_proof: 'Report counts are internally consistent by construction (' + nrep + ' of ' + nrep + ').',
      panel: panel,
      panel_block: 'Simulated panel: ' + panel[0] + ' and ' + panel[1] + ' (fictional reviewers).',
      officer_conclusion: buildConclusion(subj),
      creator_signoff: 'Generated by the JAH Data Bases boundless generator — synthetic dossier.',
      corroborating_specs: [],
      date_filed: iso(y, m, d),
      sources: ['JAH Data Bases synthetic dossier — no real-world sources; generated for the boundless archive.'],
      _cat: c, _adj: adj, _noun: noun, _phen: phen, _subj: subj,
      _nrep: nrep, _place: place, _year: year, _panel: panel,
      _y: y, _m: m, _d: d
    };
  }

  function generate(seed, opts, rnd) {
    opts = opts || {};
    var g = genDossier(rnd, opts);
    var n = (opts.baseN || 0) + 1;
    var rec = {
      id: ID_PREFIX + String(n).padStart(6, '0'),
      n: n,
      kind: g.kind,
      category: g.category,
      cat_code: g.cat_code,
      subject: g.subject,
      classification: g.classification,
      overview: g.overview,
      assessment: g.assessment,
      science_proof: g.science_proof,
      math_proof: g.math_proof,
      panel: g.panel,
      panel_block: g.panel_block,
      officer_conclusion: g.officer_conclusion,
      creator_signoff: g.creator_signoff,
      corroborating_specs: g.corroborating_specs,
      date_filed: g.date_filed,
      sources: g.sources,
      record_kind: 'synthetic',
      stamp: STAMP
    };
    rec._priv = g;
    rec._seed = seed;
    return rec;
  }

  function verify(rec) {
    var errs = [];
    var p = rec._priv;
    if (!p) return ['no private params — cannot independently verify'];
    var catOk = CATS.some(function (c) { return c[0] === p._cat[0] && c[1] === p._cat[1]; });
    if (!catOk) errs.push('category not in the archive set');
    if (rec.subject !== buildSubject(p._adj, p._noun, p._phen)) errs.push('subject mismatch');
    if (rec.classification !== buildClassification(p._cat[1])) errs.push('classification mismatch');
    if (rec.overview !== buildOverview(p._subj, p._nrep, p._place, p._year)) errs.push('overview mismatch');
    if (rec.assessment !== buildAssessment(p._subj, p._nrep)) errs.push('assessment mismatch');
    if (rec.officer_conclusion !== buildConclusion(p._subj)) errs.push('conclusion mismatch');
    if (rec.date_filed !== iso(p._y, p._m, p._d)) errs.push('date_filed mismatch');
    if (rec.panel_block !== 'Simulated panel: ' + p._panel[0] + ' and ' + p._panel[1] + ' (fictional reviewers).')
      errs.push('panel_block mismatch');
    if (!Array.isArray(rec.corroborating_specs) || rec.corroborating_specs.length !== 0)
      errs.push('synthetic dossiers must cite zero corroborating specs');
    if (rec.kind !== 'bizarre') errs.push('bad kind');
    return errs;
  }

  function validate(rec) {
    var errs = [];
    if (!rec || typeof rec !== 'object') return { ok: false, errors: ['not an object'] };
    ['id', 'kind', 'category', 'cat_code', 'subject', 'classification', 'overview',
     'assessment', 'officer_conclusion', 'date_filed', 'sources'].forEach(function (k) {
      if (rec[k] === undefined || rec[k] === null || rec[k] === '') errs.push('missing field: ' + k);
    });
    if (rec.id && !/^JAH-LEAK-\d{6}$/.test(rec.id)) errs.push('bad id format');
    if (rec._priv) errs = errs.concat(verify(rec));
    else errs.push('no private params — cannot independently verify');
    return { ok: errs.length === 0, errors: errs };
  }

  function driftCheck(rec, archiveSample) {
    var errs = [];
    (archiveSample || []).forEach(function (a) {
      var s = a.subject || a[1];
      if (s && String(s).toLowerCase().replace(/\s+/g, ' ') === String(rec.subject).toLowerCase().replace(/\s+/g, ' '))
        errs.push('duplicate of archived dossier subject: ' + rec.subject);
    });
    return { ok: errs.length === 0, errors: errs };
  }

  function themedGenerate(seed, opts, rnd, themeSamples) {
    var rec = generate(seed, opts, rnd);
    if (themeSamples && themeSamples.length) {
      var t = themeSamples[Math.floor(rnd() * themeSamples.length)];
      var nums = String(JSON.stringify(t)).match(/\d+/g);
      if (nums && nums.length) {
        var rec2 = generate(seed + (parseInt(nums[0], 10) % 1000), opts,
          JAHDB.prng(JAHDB.hashStr(String(seed) + nums[0])));
        rec2.id = rec.id; rec2.n = rec.n;
        return rec2;
      }
    }
    return rec;
  }

  JAHDB.registerGenerator('leaks', {
    version: VERSION,
    generate: generate,
    validate: validate,
    driftCheck: driftCheck,
    themedGenerate: themedGenerate,
    types: ['bizarre']
  });
})();
