/* ✳ SIGNATURE — JAH Product Data Base generator. Property of Justin Addam Higgins (JAH).
   Boundless generator: produces NEW products in the archive's format
   (id, name, dept, price, src, stype, sid, blurb, seed). Deterministic:
   same seed + version => same record. Names are built constructively from
   the department's real archive vocabulary; an INDEPENDENT verifier rebuilds
   the name from the word indices and checks every word against that
   department's vocabulary before acceptance. All products are free forever —
   price is always 0. */
(function () {
  'use strict';
  var VERSION = 'jahdb-mall-1.0';
  var ID_PREFIX = 'JAH-PROD-';

  function ri(rnd, a, b) { return a + Math.floor(rnd() * (b - a + 1)); }
  function pick(rnd, arr) { return arr[Math.floor(rnd() * arr.length)]; }
  function shuffle(rnd, arr) {
    arr = arr.slice();
    for (var i = arr.length - 1; i > 0; i--) {
      var j = Math.floor(rnd() * (i + 1)), t = arr[i]; arr[i] = arr[j]; arr[j] = t;
    }
    return arr;
  }

  /* real departments + name vocabulary sampled from the archive product names */
  var DEPTS = {
    'AI & Software': ['helper', 'writer', 'planner', 'guide', 'maker', 'coach', 'builder', 'finder', 'teacher', 'tutor', 'organizer', 'tracker', 'fixer', 'explainer', 'reader', 'trainer', 'picker', 'designer', 'mechanic', 'code', 'language', 'care', 'info'],
    'Compute': ['signature', 'computer', 'quantum', 'silicon', 'board', 'transistor', 'processor', 'node', 'device', 'compute', 'chip', 'array', 'memory', 'photonic', 'qubit', 'soc', 'loom', 'logic', 'scale', 'atom', 'cpu', 'digital', 'control', 'unit', 'fpga', 'gpu'],
    'Inventions': ['method', 'apparatus', 'deterministic', 'line', 'series', 'suite', 'array', 'hub', 'lab', 'console', 'toolkit', 'module', 'portable', 'concept', 'object', 'device', 'engineering', 'detection', 'analysis', 'future', 'preparation', 'planning', 'process', 'encoding', 'math'],
    'Knowledge': ['future', 'signature', 'economics', 'toolkit', 'challenger', 'console', 'array', 'hub', 'token', 'lab', 'utility', 'media', 'products', 'module', 'suite', 'water', 'transportation', 'secret', 'detection', 'analysis', 'deterministic', 'production', 'decomposer', 'tokenizer', 'broker'],
    'Tools': ['solver', 'evaluator', 'area', 'radius', 'volume', 'circle', 'box', 'sphere', 'rectangle', 'triangle', 'base', 'height', 'prompt', 'chat', 'suggester', 'text', 'snippet', 'link', 'finder', 'checker', 'builder', 'maker']
  };
  var DEPTNAMES = Object.keys(DEPTS);

  function title(w) { return w.charAt(0).toUpperCase() + w.slice(1); }

  function generate(seed, opts, rnd) {
    opts = opts || {};
    var dept = opts.dept && DEPTS[opts.dept] ? opts.dept : pick(rnd, DEPTNAMES);
    var vocab = DEPTS[dept];
    var k = ri(rnd, 2, 3);
    var words = shuffle(rnd, vocab).slice(0, k);
    var name = words.map(title).join(' ');
    var n = (opts.baseN || 0) + 1;
    var id = ID_PREFIX + String(n).padStart(6, '0');
    var rec = {
      id: id,
      n: n,
      name: name,
      dept: dept,
      price: 0,
      src: 'JAH Product Data Base',
      stype: 'generated',
      sid: id,
      blurb: name + ' — a ' + dept + ' product generated by the JAH Product Data Base boundless generator. Free forever.',
      seed: String(seed)
    };
    var pub = {};
    ['id', 'n', 'name', 'dept', 'price', 'src', 'stype', 'sid', 'blurb', 'seed'].forEach(function (k) { pub[k] = rec[k]; });
    pub._priv = { dept: dept, words: words, name: name };
    return pub;
  }

  /* independent re-verification: rebuild the name from the word indices */
  function verify(rec) {
    var errs = [];
    var p = rec._priv;
    if (DEPTNAMES.indexOf(p.dept) < 0) errs.push('unknown dept');
    else p.words.forEach(function (w) {
      if (DEPTS[p.dept].indexOf(w) < 0) errs.push('word not in dept vocabulary: ' + w);
    });
    if (p.words.map(title).join(' ') !== rec.name) errs.push('name does not rebuild from word indices');
    if (rec.price !== 0) errs.push('price must be 0 (free forever)');
    if (rec.stype !== 'generated') errs.push('stype must be generated');
    if (rec.sid !== rec.id) errs.push('sid must equal id');
    if (rec.dept !== p.dept) errs.push('dept mismatch');
    return errs;
  }

  function validate(rec) {
    var errs = [];
    if (!rec || typeof rec !== 'object') return { ok: false, errors: ['not an object'] };
    ['id', 'name', 'dept', 'price', 'src', 'stype', 'sid', 'blurb', 'seed'].forEach(function (k) {
      if (rec[k] === undefined || rec[k] === null || rec[k] === '') errs.push('missing field: ' + k);
    });
    if (rec.id && !/^JAH-PROD-\d{6}$/.test(rec.id)) errs.push('bad id format');
    if (rec.dept && DEPTNAMES.indexOf(rec.dept) < 0) errs.push('bad dept');
    if (rec._priv) errs = errs.concat(verify(rec));
    else errs.push('no private params — cannot independently verify');
    return { ok: errs.length === 0, errors: errs };
  }

  function driftCheck(rec, archiveSample) {
    var errs = [];
    (archiveSample || []).forEach(function (a) {
      var nm = a.name || a.n;
      if (nm && String(nm).toLowerCase() === String(rec.name).toLowerCase())
        errs.push('duplicate of archived product name: ' + rec.name);
    });
    return { ok: errs.length === 0, errors: errs };
  }

  function themedGenerate(seed, opts, rnd, themeSamples) {
    var rec = generate(seed, opts, rnd);
    if (themeSamples && themeSamples.length) {
      var t = themeSamples[Math.floor(rnd() * themeSamples.length)];
      var nums = String(JSON.stringify(t)).match(/\d+/g);
      if (nums && nums.length) {
        var rec2 = generate(seed + (parseInt(nums[0], 10) % 1000), opts,
          JAHDB.prng(JAHDB.hashStr(String(seed) + nums[0])));
        rec2.id = rec.id; rec2.n = rec.n;
        return rec2;
      }
    }
    return rec;
  }

  JAHDB.registerGenerator('mall', {
    version: VERSION,
    generate: generate,
    validate: validate,
    driftCheck: driftCheck,
    themedGenerate: themedGenerate,
    depts: DEPTNAMES
  });
})();
